package graphiceditormvc;

/**
 * Una finestra di dialogo che fornisce una vista testuale dei documenti di tipo Model:
 * elenca, per ogni forma, il tipo, le coordinate (X,Y) del punto in alto a sinistra, 
 * larghezza e altezza [W,H] e colore di riempimento.
 * 
 * @author mauropamiro
 */
public class WndListaView extends java.awt.Dialog {

    private Model documento;

    /**
     * Crea una nuova finestra WndListaForme, associandole il documento 
     * di tipo Model da visualizzare.
     * 
     * @param   parent      la finestra padre
     * @param   modal       true se la finestra è modale, false altrimenti
     * @param   documento   il documento di tipo Model da visualizzare
     */
    public WndListaView(java.awt.Frame parent, boolean modal, Model documento) {
        super(parent, modal);
        initComponents();
        this.documento=documento;
    }

    /**
     * Associa un documento di tipo Model alla vista
     * 
     * @param documento il documento da associare alla vista
     */
    public void setDocumento(Model documento) {
        this.documento = documento;
    }
    
    /**
     * Chiude la finestra
     */
    public void chiudi(){
        setVisible(false);
    }
    
    /**
     * Aggiorna la vista del documento
     */
    public void aggiorna(){
        if(documento!=null){
            txtArea.setText(documento.toString());
            repaint();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        btnChiudiLista = new javax.swing.JButton();

        setLocationRelativeTo(null);
        setMinimumSize(new java.awt.Dimension(600, 500));
        setResizable(false);
        setTitle("Elenco Forme");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        txtArea.setEditable(false);
        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        btnChiudiLista.setText("Chiudi");
        btnChiudiLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChiudiListaActionPerformed(evt);
            }
        });
        add(btnChiudiLista, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        chiudi();
    }//GEN-LAST:event_closeDialog

    private void btnChiudiListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChiudiListaActionPerformed
        chiudi();
    }//GEN-LAST:event_btnChiudiListaActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        aggiorna();
    }//GEN-LAST:event_formComponentShown

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChiudiLista;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtArea;
    // End of variables declaration//GEN-END:variables
}
