package graphiceditormvc;

import java.awt.Frame;
import java.awt.Point;
import java.util.Observable;
import java.util.Observer;
import javax.swing.JDialog;

/**
 * Una finestra di dialogo in cui viene visualizzata una rappresentazione testuale del documento
 * 
 * @author mauropamiro
 */
public class WndTextView extends JDialog implements Observer{
    
    /**
     * Costruttore: crea la finestra
     * 
     * @param main la finestra principale
     */
    public WndTextView(Frame main) {
        super(main, false);
        initComponents();
        // La finestra viene visualizzata alla destra della finestra principale
        setLocation(new Point(main.getX()+main.getWidth()*3/4,main.getY()+50));
    }

    /**
     * Aggiorna la vista testuale del documento.
     * 
     * @param o il Model che ha richiesto l'aggiornamento
     * @param arg eventuali parametri (non utilizzati in questo caso)
     */
    @Override
    public void update(Observable o, Object arg) {
        String testo=((Model)o).toString();
        txtArea.setText(testo);   
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();

        setTitle("Elenco Forme");
        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(300, 400));
        setResizable(false);

        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtArea;
    // End of variables declaration//GEN-END:variables
}
